### ISSUE TITLE
El archivo donde se guarda la partida es alterable y no hay consecuencias.

### ISSUE THREAD

**Issue by federicofranco97** [diegomoran777/generala#89]
Proyecto: Generala
Version: ?
Plataforma: Pc - Windows 10 64b
Gravedad: critical
Descripcion: El archivo donde se guarda la partida es editable y la partida carga despues normalmente. No verifica si el archivo fue alterado o no.
Paso a paso:
1.abrir el juego
2.crear un juego de tamaño a eleccion
3.guardar y cerrar el juego
4.modificar el archivo donde se guarda la informacion 
5.iniciar el juego y cargar la partida modificada
Tasa de reproduccion:100%

**Comment by diegomoran777** [comment]
won t fix-Ya que no era pedido no es necesario realizar esa encriptacion
