### ISSUE TITLE
No muestra dados separados

### ISSUE THREAD

**Issue by andreslcm** [diegomoran777/generala#92]
Juego: Generala
SO: Windows 10 64 bits
Descripción: al utilizar la opción de imprimir los dados separados, no se muestra nada.
Tasa de reproducción: 100 %
Reproducción:
Después de separar algunos dados dentro del juego, escoger la opción de imprimir dados separados.

**Comment by diegomoran777** [comment]
Avisa en una pantalla que no hay separados ya que todavia no se han separado dados, no seria un error
