### ISSUE TITLE
Los jugadores pueden tener el mismo nombre

### ISSUE THREAD

**Issue by CacoRod** [diegomoran777/generala#93]
Proyecto: Generala
Version: 1.00
Plataforma: Pc - Windows 7 64b -8 gb ram
Gravedad: medio
Descripcion: Podria estar en ambos idiomas
Paso a paso: al ingresar los nombres de los jugadores, ingresa el mismo nombre para distintos jugadores
Tasa de reproduccion:100%

**Comment by diegomoran777** [comment]
que los jugadores tengan el mismo nombre no es un error. Ademas esta marcada la ronda y vuelta de cada uno.
