### ISSUE TITLE
El juego no incluye instrucciones de como jugar

### ISSUE THREAD

**Issue by CacoRod** [diegomoran777/generala#94]
Proyecto: Generala
Version: 1.00
Plataforma: Pc - Windows 7 64b -8 gb ram
Gravedad: min
Descripcion: El juego necesita instrucciones
Paso a paso: al comenzar el juego no hay intrucciones de como jugar
Tasa de reproduccion:100%

**Comment by beelanselm** [comment]
Dado que no era una especificación del proyecto añadir instrucciones y consideramos que es un juego muy popular, cuya forma de jugar se encuentra explicada en muchos sitios y es fácil acceder a ellas, decidimos no incluir las mismas.
