### ISSUE TITLE
imprimir tabla de resultados en el primer turno despliega información incoherente

### ISSUE THREAD

**Issue by CacoRod** [diegomoran777/generala#95]
Proyecto: generala
Version: 1
Plataforma: Pc - Windows 10 64b -8 gb ram
Gravedad: trivial- min
Descripcion: imprimir tabla de resultados en el primer turno despliega información incoherente
Paso a paso: comenzar partida. Ingresar jugadores y a la primera oportunidad, seleccionar "imprimir tabla de resultados"
Tasa de reproduccion:100%

**Comment by diegomoran777** [comment]
Ya que no hay hay jugadas tachadas en valor 0 o jugadas  anotadas con valor , el valor por defecto es -1 ya que nulo no seria una buena practica.
